; MSC Device OS
; XIAO ESP32S3 Sense

[platformio]
src_dir = firmware/app

[env:xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.partitions = huge_app.csv

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=3

lib_deps =
    h2zero/NimBLE-Arduino
    bblanchon/ArduinoJson