// MSC Device OS - Global Configuration

#ifndef DEVICE_CONFIG_H
#define DEVICE_CONFIG_H

#define MSC_FIRMWARE_VERSION "0.1.0"

#define MSC_DEVICE_NAME "MSC-SETUP"

#define MSC_BLE_SERVICE_UUID \
"6E400001-B5A3-F393-E0A9-E50E24DCCA9E"

#define MSC_WIFI_TIMEOUT_MS 15000

#endif